### PR TITLE
Issue51 fix skos

### LINKED ISSUE #51: EventType subClassOf skos:Concept?
What is the use case for this?

https://github.com/tibonto/aeon/blob/77a0ce7d192d663a0c0bc83ca149a231af558565/aeon.ttl#L1467

It looks strange to me, but without knowing the intended use case I can't tell whether it's good or bad.

### PR DESCRIPTION
**Pull request by StroemPhi**
closes #51

### CODE REVIEW

**Comment by StroemPhi** [comment]
@clange it would be great if you could have a look over this, since you pointed me out my wrong use of skos:Concept. 
As I wrote in #51 I now want to discard the use of skos in AEON altogether. So I subsumed the event type under iao:plan specification and renamed it academic event type specification. The reasoning behind it is that, since an academic event is always a planned process, there must be a plan specification which determines what kind of academic event it is. In it's most primitive form this would mean that the organizers just say, we plan to make this a conference. But having it an ia:plan specification also means that it can have objective and action specification, plus I added also that it can have condition specifications. With this we have the basis to also say something about other format (event type specific) things. E.g. a submission deadline is a condition specification which is part of the event type specification and which specifies the condition until when and where the submission must be send to.

**Comment by andrecastro0o** [comment]
@StroemPhi I see the following errors from ROBOT report:
It would be nice to understand why the duplicate label error  is happening. Is it because those terms have both `rdfs:label` and ` obo:IAO_0000115` if so we might need to change the configure robot report to not assume that coimbination from being a duplicate label or make it trow WARN at duplicate labels.
```
ERROR	missing_label	https://github.com/tibonto/aeon#congress	rdfs:label	
ERROR	missing_label	https://github.com/tibonto/aeon#talk	rdfs:label	
ERROR	duplicate_label	IAO:0020015	rdfs:label	personal name@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#personal_name	rdfs:label	personal name@en
ERROR	duplicate_label	IAO:0020000	rdfs:label	identifier@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#ID	rdfs:label	identifier@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#AEON_0000030	rdfs:label	fee@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#fee	rdfs:label	fee@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#AEON_0000023	rdfs:label	country@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#country	rdfs:label	country@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#contact_person	rdfs:label	contact person@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#contact_person_name	rdfs:label	contact person@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#AEON_0000022	rdfs:label	city@en
ERROR	duplicate_label	https://github.com/tibonto/aeon#city	rdfs:label	city@en
```

**Comment by StroemPhi** [comment]
@andrecastro0o the two missing labels I've definitely overlooked. The other errors are still due to me not having had the time to finish the data property clean up. But in order ot not get annoying error messages, I've changed them now here, although they have nothing to do with the #51 themself. Now all tests are passed. So what remains is only a feedback on me making event type an iao: plan spec ;)

**Comment by StroemPhi** [comment]
> 
> 
> @StroemPhi I see the following errors from ROBOT report:
> It would be nice to understand why the duplicate label error is happening. Is it because those terms have both `rdfs:label` and ` obo:IAO_0000115` if so we might need to change the configure robot report to not assume that coimbination from being a duplicate label or make it trow WARN at duplicate labels.
> 
> ```
> ERROR	missing_label	https://github.com/tibonto/aeon#congress	rdfs:label	
> ERROR	missing_label	https://github.com/tibonto/aeon#talk	rdfs:label	
> ERROR	duplicate_label	IAO:0020015	rdfs:label	personal name@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#personal_name	rdfs:label	personal name@en
> ERROR	duplicate_label	IAO:0020000	rdfs:label	identifier@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#ID	rdfs:label	identifier@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#AEON_0000030	rdfs:label	fee@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#fee	rdfs:label	fee@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#AEON_0000023	rdfs:label	country@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#country	rdfs:label	country@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#contact_person	rdfs:label	contact person@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#contact_person_name	rdfs:label	contact person@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#AEON_0000022	rdfs:label	city@en
> ERROR	duplicate_label	https://github.com/tibonto/aeon#city	rdfs:label	city@en
> ```

@andrecastro0o we don't need to change anything with the ROBOT report. this was definitely wrongly named in AEON, so my fault.

**Pull request merged**
