### PR TITLE
Draft: removed aeon:SMW_datatype

### LINKED ISSUE #98: Remove SMW related annotation properties
We had defined annotation properties (`aeon:SMW_datatype`, `aeon:SMW_import_info`, `aeon:WikidataLabel` & `aeon:WikidataURI`) which are needed only in the context of the ConfIDent project and where meant to ease the import of AEON into a clean SMW instance. For the general use of AEON this is not need and also the [ontology2smw](https://github.com/TIBHannover/ontology2smw) tool used for an automated ontology import into a SMW doesn't seem to need this anymore. 

Therefore those properties should be purged from AEON and might only be implemented in a fork ment to be used as an application ontology.

### PR DESCRIPTION
**Pull request by andrecastro0o**
closes #98 

keep it open @StroemPhi  I need to use the PR changes view to see what robot is doing.

e23c37af39c660bb4a5300184cc72b8dd2d5ceb0 removed `aeon:SMW_datatype` but robot also removed a few prefixes :-1:  will revert and try to get it under the right beahviour

### CODE REVIEW

**Comment by andrecastro0o** [comment]
@StroemPhi 
From my part the PR is ready.

I added a:
* prefixes.json file - this is useful to work with robot + ttl - as described in ontodev/robot#846
*  scripts dir -  so we can collect the scripts we have been using, but if you like to keep the dir clean, perhaps put it somewhere else, like a Repo wiki or Gist (although i have no idea) how to share the later.

**Comment by andrecastro0o** [comment]
@StroemPhi perhaps is useful to squash the commits upon merge - too many of them to start - not a clean history :grimacing:

**Review by StroemPhi — APPROVED** [review]
looking good, thanks @andrecastro0o !

**Comment by StroemPhi** [comment]
> 
> 
> @StroemPhi
> From my part the PR is ready.
> 
> I added a:
> 
>     * prefixes.json file - this is useful to work with robot + ttl - as described in [ontodev/robot#846](https://github.com/ontodev/robot/issues/846)
> 
>     * scripts dir -  so we can collect the scripts we have been using, but if you like to keep the dir clean, perhaps put it somewhere else, like a Repo wiki or Gist (although i have no idea) how to share the later.

The repo clean up will be addressed later in #101

**Pull request merged**
